trigger:
  - master

pool: vikram-first-self-agent-pool

stages:
- stage: test_stage
  jobs: 
    - job: test_jobs
      steps:
      - bash: echo "hello world by vikram"
- template: maven_build_job.yml