trigger:
  - master

pool: vikram-first-self-agent-pool

stages:
- stage: test_stage
  pool: vikram-first-self-agent-pool
  jobs:
    - job: test_jobs
      steps:
      - bash: echo "hello world by vikram"
- stage: maven_build_stage
  jobs:
    - template: maven_build_job.yml