trigger:
  - master

pool: vikram-first-self-agent-pool

stages:
- stage: test_stage
  jobs: 
    - job: test_jobs
      steps:
      - bash: echo "hello world by vikram"
- stage: maven_build_stage
  jobs:
    - template: maven_build_job.yml
      parameters:
        build_job_name  : parameter_build_job