parameters:
  - name: pool
    type: object
    default:
      name: vikram-first-self-agent-pool

jobs:
  - job: build_job_maven
    pool: ${{ parameters.pool }}
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: MyWebApp/pom.xml
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'