parameters:
  build_job_name: ''

jobs:
  - job: ${{ parameters.build_job_name }}
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: MyWebApp/pom.xml
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'